#                                 

format = """
$time\
[](fg:#425047 bg:#3A515D)\
[](fg:#3A515D bg:#3A515D)\
$username\
[](fg:#3A515D bg:#4D4C43)\
$directory\
[](fg:#4d4c43 bg:#514045)\
$git_branch\
$git_status\
[ ](fg:#514045)\
"""

right_format = """
[](fg:#232A2e)\
$time\
$character
"""

[username]
show_always = true
style_user = "fg:#7fbbb3 bg:#3A515D"
style_root = "fg:#7fbbb3 bg:#3A515D"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:#DBBC7F bg:#4d4c43"
format = "[ $path ]($style)"
disabled = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#E69875 bg:#514045"
format = '[ $symbol $branch ]($style)'
disabled = false

[git_status]
style = "fg:#E69875 bg:#514045"
format = '[$all_status$ahead_behind ]($style)'
disabled = false

# Start languages and tools #

[c]
symbol = ""
style = "fg:#D3C6AA bg:#543A48"
format = '[ $symbol ($version) ]($style)'
disabled = false

[kubernetes]
style = "fg:#D3C6AA bg:#3A515D"
format = '[ on ﴱ ($user on )($cluster in )$context \($namespace\) ]($style)'
disabled = false

[gcloud]
symbol = " "
style = "fg:#D3C6AA bg:#425047"
format = '[ on $symbol $account(@$domain)(\($region\)) ]($style) '
# format = '[ on $symbol account@company.iam.gserviceaccount.com(\($region\)) ]($style) ' # for testing purposes
disabled = false

[golang]
symbol = ""
style = "fg:#D3C6AA bg:#475258"
format = '[ $symbol ($version) ]($style)'
disabled = false

[java]
symbol = ""
style = "fg:#D3C6AA bg:#3D484D"
format = '[ $symbol ($version) ]($style)'
disabled = false

[lua]
symbol = ""
style = "fg:#D3C6AA bg:#343F44"
format = '[ $symbol ($version) ]($style)'
disabled = false

[nodejs]
symbol = ""
style = "fg:#D3C6AA bg:#405447"
format = '[ $symbol ($version) ]($style)'
disabled = false

[package]
symbol = ""
style = "fg:#D3C6AA bg:#543A48"
format = '[ $symbol ($version) ]($style)'
disabled = false

[php]
symbol = ''
style = "fg:#D3C6AA bg:#4F5B93"
format = '[ $symbol ($version) ]($style)'
disabled = false

[python]
symbol = ''
style = "fg:#000000 bg:#ffdf76"
format = '[ $symbol ($version) ]($style)'
disabled = false

[rust]
symbol = ""
style = "fg:#D3C6AA bg:#a72145"
format = '[ $symbol ($version) ]($style)'
disabled = false

# End languages and tools #

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#A7C080 bg:#425047"
format = '[ 󱑂 $time ]($style)'

[cmd_duration]
style = "fg:#000000 bg:yellow"
format = "[ took $duration ]($style)"

[character]
format = " $symbol"