#!/bin/python3

import sys
from pydbus import SessionBus
import cv2
import numpy as np
import urllib.request

bus = SessionBus()
spotify_object = None
try:
    spotify_object = bus.get(
        "org.mpris.MediaPlayer2.spotify", "/org/mpris/MediaPlayer2"
    )
except:
    pass

args = sys.argv
if len(args) != 2:
    print("Error")
else:
    if args[1] == "song":
        if spotify_object:
            print(spotify_object.Metadata["xesam:title"])
        else:
            print("Offline")
    elif args[1] == "time":
        print(
            int(spotify_object.Position)
            * 100
            / int(spotify_object.Metadata["mpris:length"])
        )
    elif args[1] == "artist":
        if spotify_object:
            print("".join(spotify_object.Metadata["xesam:artist"]))
        else:
            print("Offline")
    elif args[1] == "status":
        if spotify_object:
            if spotify_object.PlaybackStatus == "Paused":
                print("󰐌")
            else:
                print("󰏥")
        else:
            print("喇")
    elif args[1] == "cover":
        url = spotify_object.Metadata["mpris:artUrl"]
        req = urllib.request.urlopen(url)
        arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
        img = cv2.imdecode(arr, 0)
        cv2.imwrite("images/cover.jpg", img)
        print("images/cover.jpg")
    elif args[1] == "toggle":
        spotify_object.PlayPause()
    elif args[1] == "next":
        spotify_object.Next()
    elif args[1] == "prev":
        spotify_object.Previous()
    else:
        pass
