local light = {}
local l = "#888888"
local d = "#eeeeee"
light.bg = "#FDFDFD"
light.light_red = l
light.dark_red = d
light.light_green = l
light.dark_green = d
light.light_yellow = l
light.dark_yellow = d
light.light_blue = l
light.dark_blue = d
light.light_purple = l
light.dark_purple = d
light.light_aqua = l
light.dark_aqua = d
light.light_gray = l
light.dark_gray = d
light.fg = "#555555"
light.bg0_h = "#EFEFEF"
light.bg1 = "#F4F4F4"
light.bg2 = "#efefef"
light.bg3 = "#e6e6e6"
light.bg4 = "#e0e0e0"
light.bg0_s = "#bdbdbd"
light.fg0 = "#555555"
light.fg1 = "#939393"
light.fg2 = "#707070"
light.fg3 = "#E6E6E6"
light.fg4 = "#939393"
light.light_orange = l
light.dark_orange = d

local dark = {}
local l = "#eeeeee"
local d = "#666666"
dark.bg = "#262626"
dark.light_red = l
dark.dark_red = d
dark.light_green = l
dark.dark_green = d
dark.light_yellow = l
dark.dark_yellow = d
dark.light_blue = l
dark.dark_blue = d
dark.light_purple = l
dark.dark_purple = d
dark.light_aqua = l
dark.dark_aqua = d
dark.light_gray = l
dark.dark_gray = d
dark.fg = "#dddddd"
dark.bg0_h = "#11111"
dark.bg1 = "#323232"
dark.bg2 = "#3d3d3d"
dark.bg3 = "#424242"
dark.bg4 = "#4d4d4d"
dark.bg0_s = "#5d5d5d"
dark.fg0 = "#dddddd"
dark.fg1 = "#cacaca"
dark.fg2 = "#f0f0f0"
dark.fg3 = "#818181"
dark.fg4 = "#cacaca"
dark.light_orange = l
dark.dark_orange = d

return {
    light = light,
    dark = dark
}
